# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160714_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='path',
            field=models.TextField(default='1.jpg'),
            preserve_default=False,
        ),
    ]
