# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_subreddit_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subreddit',
            options={'ordering': ('-popularity',)},
        ),
    ]
